### ISSUE TITLE
Weird plugin behavior

### ISSUE THREAD

**Issue by lucasmartins** [integra-consultores/advanced-membership-management#1]
It seems the plugin isn't getting linked correctly into Redmine, when I test a simple task like deleting a user, I get an "Internal Error" page and the following error on the server log:

```
NameError (uninitialized constant User::AutomaticMembership):
  app/controllers/users_controller.rb:174:in `destroy'
```

Do you have this plugin working in your environment? Could you send me your Redmine folder so I can replicate your environment here?

I want to develop automated tests for this plugin.

Thanks a lot,

Regards,

Lucas.

**Comment by bishma-stornelli** [comment]
Hello @lucasmartins , sadly I don't have this working in my environment because I changed my computer recently. Nevertheless, I'll try to install it this week and I'll be informing you.

**Comment by lucasmartins** [comment]
Thanks a lot, I really appreciate your help.

**Comment by bishma-stornelli** [comment]
This was the step I followed and I didn't find any error:

```
git clone git@github.com:redmine/redmine.git
cd redmine/
git checkout 2.2.2
# sqlite3 configured in development
bundle install --without postgresql
rake db:migrate
rake generate_secret_token
rake redmine:load_default_data
git submodule add git@github.com:integra-consultores/advanced-membership-management.git plugins/advanced_membership_management
rake redmine:plugins
```

After that:
1. Login with admin
2. Create a new user
3. Add automatic memberships for that user
4. Delete user

Everything worked fine.

**Comment by bishma-stornelli** [comment]
Tested in redmine 2.2.3 and didn't get the error either. What environment are you using? 2.3.x?

**Comment by lucasmartins** [comment]
I followed your instructions and it worked well! Thanks.

I think my problem is in the SQL generation for the database, I get suspicious errors...

I'll investigate it further and post back my results,

Thanks again!
