### ISSUE TITLE
Plugin install at Redmine 2.3.0 stable problem

### ISSUE THREAD

**Issue by Luckyvb** [integra-consultores/advanced-membership-management#2]
rake redmine:plugins:migrate RAILS_ENV=production throw exception

/opt/redmineTEST/plugins/advanced-membership-management-master/lib/advanced_membership_management/member_patch.rb:157: odd number list for Hash
        @roles_changes = { original: self.role_ids }
                                    ^
/opt/redmineTEST/plugins/advanced-membership-management-master/lib/advanced_membership_management/member_patch.rb:157: syntax error, unexpected ':', expecting '}'
        @roles_changes = { original: self.role_ids }

**Comment by bishma-stornelli** [comment]
That problem raises from running the plugin with ruby 1.8.7. It was implemented using the new ruby 1.9.3 hash syntax. If you don't want to upgrade to ruby 1.9.3 you can change all hash syntax from:

```
{ my_key: my_value }
```

to:

```
{ :my_key => my_value }
```

Also, you can make a pull request to make this plugin compatible with ruby 1.8.7.
